### ISSUE TITLE
Fix leaky dialog warning in sample

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#51]
Our old friend wants attention. I'm hoping we can use a lifecycle observer instead of the usual hacks, once #50 lands and we move to AndroidX.

```
android.view.WindowLeaked: Activity com.squareup.sample.authgameapp.ShellActivity has leaked window DecorView@9920615[] that was originally added here
    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
    at android.app.Dialog.show(Dialog.java:330)
    at com.squareup.sample.authgameapp.ShellCoordinator.ensureDialog(ShellCoordinator.kt:95)
    at com.squareup.sample.authgameapp.ShellCoordinator.access$ensureDialog(ShellCoordinator.kt:41)
    at com.squareup.sample.authgameapp.ShellCoordinator$attach$1.accept(ShellCoordinator.kt:65)
```

Maybe want this too:

```
private val Context.activity: AppCompatActivity
  get() {
    var wrapper = this as ContextWrapper
    var activity: Activity? = null
    do {
      if (wrapper is Activity) {
        activity = wrapper
      } else {
        wrapper = wrapper.baseContext as ContextWrapper
      }
    } while (activity == null)
    return activity as AppCompatActivity
  }
```

**Comment by zach-klippenstein** [comment]
AndroidX landed in #59, so this is no longer blocked.
